# Generated by Django 5.1.3 on 2024-11-29 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_journalentry_options_journalentry_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='storage.shelf', verbose_name='Стеллаж'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
